version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DOCKER_DB_PORT}:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      - db
    working_dir: /home/node/app
    ports:
      - ${PORT}:${PORT}
    # command: "npm start:dev"
    command: npm run start
    volumes:
      - .:/home/node/app
    deploy:
        resources:
            limits:
              memory: 300M